# Generated by Django 4.2 on 2023-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_is_deleted_profile_isblocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
