# Generated by Django 4.2.2 on 2023-06-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_gameversion_path_to_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='thumbnail',
        ),
    ]
